name: flutter_skeleton_project
description: "A skeleton Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.7
  go_router: ^14.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.4.0
  get_it: ^7.7.0
  dio: ^5.5.0+1
  floor: ^1.5.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  floor_generator: ^1.5.0


flutter:
  uses-material-design: true
  assets:
    - assets/translations/